barbershop/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('', views.appointment, name='appointment'),
    path('barber/', views.appointment_barber, name='appointment-barber'),
    path('thanks/', views.thanks_page, name='thanks_page'),
]

barbershop/barbershop/urls.py
from django.urls import path
from . import views

app_name = 'barbershop'

urlpatterns = [
    path('', views.barbershop, name='barbershop')
]

barbershop/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('barbershop.urls')),
    path('appointment/', include('appointment.urls')),
    path('user/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barbershop/user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('account/', views.user_account, name='user_account'),
    path('edit-account/', views.edit_account, name='edit-account'),
]

barbershop/appointment/models.py
from django.db import models
from barbershop.models import Barbers, Price
from user.models import Profile

class Appointment(models.Model):
    dt = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=20, verbose_name="Имя")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    day = models.DateField(verbose_name="День")
    time = models.TimeField(verbose_name="Время")
    barber = models.ForeignKey(Barbers, on_delete=models.CASCADE, null=True, verbose_name="Барбер")
    service = models.ForeignKey(Price, on_delete=models.SET_NULL, max_length=100, null=True, verbose_name="Услуга")
    client = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Клиент")

    def __sts__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-dt']

barbershop/appointment/views.py
from django.shortcuts import render
from .models import Appointment
from barbershop.models import Barbers, Price, Tag
from user.models import Profile
from datetime import datetime, timedelta
from django.contrib import messages

def appointment_barber(request):
    barber_names = Barbers.objects.all()

    dict_obj = {
            'barber_names': barber_names,
            }

    return render(request, 'appointment/appointment_barber.html', dict_obj)

def appointment(request):
    all_time = ['08:00', '09:00', '10:00', '11:00',
            '12:00', '13:00', '14:00', '15:00',
            '16:00', '17:00', '18:00', '19:00']
    
    yesterday = datetime.today()
    min_day_value = yesterday.strftime("%Y-%m-%d")
    max_day_value = yesterday + timedelta(days=14)
    max_day_value = max_day_value.strftime("%Y-%m-%d") 
    price_list = Price.objects.all()



    if request.GET.get('date') is None:
        barber = request.POST['barber']

        if barber:
            days = Barbers.objects.get(barber_name=barber).tag_set.all()
            days_list = []
            for obj in days:
                days_list.append(int(obj.days))
            print(days_list)
            list_holiday = ['Воскресенье', 'Понедельник','Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота']
            list_holiday2 = []
            for i in range(len(list_holiday)):
                for day in days_list:
                    if i == day:
                        list_holiday2.append(list_holiday[i])
            print(list_holiday2)
        
            dict_obj = {
                'min_day_value': min_day_value,
                'max_day_value': max_day_value,
                'all_time': all_time,
                'barber': barber,
                'step_1': True,
                'step_2': False,
                'step': 'Шаг 1',
                'days_list': days_list,
                'list_holiday2': list_holiday2,
                }
        else:
            messages.error(request, 'Выберите барбера')
            return render(request, 'barbershop/barbershop.html')
        
        return render(request, 'appointment/appointment.html', dict_obj)
    else:
        barber = request.GET.get('barber')
        print(barber)
        date = request.GET.get('date')

        if barber and date:
            appointments = Appointment.objects.filter(day=request.GET.get('date'), barber_id=Barbers.objects.get(barber_name=barber).id).all()
            barber_name = Barbers.objects.get(barber_name=barber)
        else:
            messages.error(request, 'Выберите дату')
            return render(request, 'barbershop/barbershop.html')

        client = ''

        if request.user.is_authenticated == True:
            client = Profile.objects.get(username=request.user.username)

        for obj in appointments:
            all_time.remove(obj.time.strftime("%H:%M"))

        if not all_time:
            error_switch = True
            message = '(Занят)'
            
        else:
            error_switch = False
            message = ''

        dict_obj = {
            'min_day_value': min_day_value,
            'max_day_value': max_day_value,
            'all_time': all_time,
            'barber': request.GET.get('barber'),
            'barber_name': barber_name,
            'price_list': price_list,
            'step_1': False,
            'step_2': True,
            'step': 'Шаг 2',
            'choised_day': request.GET.get('date'),
            'message': message,
            'error_switch': error_switch,
            'client': client
            }
        
        return render(request, 'appointment/appointment.html', dict_obj)

def thanks_page(request):
    if request.POST:
        name = request.POST['name']
        phone = request.POST['phone']
        day = request.POST['date']
        time = request.POST['time']
        barber_id = request.POST['barber_id']
        user_id = request.POST['user_id']
        service = request.POST['service']

        if request.user.is_authenticated == True:
            if time and service:
                service_id = Price.objects.get(service = service).id

                element = Appointment(name = name,
                phone = phone,
                day = day,
                time = time,
                barber_id = barber_id,
                service_id = service_id,
                client_id = user_id,
                )

                element.save()

                count_appointments = Appointment.objects.filter(client_id=request.user.id).count()
                message_discount = ''
                
                if count_appointments % 2 == 0:
                    message_discount = "Эта стрижка для вас бесплатна!"

                dict_obj = {
                    'name': name,
                    'day': day,
                    'time': time,
                    'message_discount': message_discount
                    }
                
                return render(request, 'appointment/thanks.html', dict_obj)

            else:
                messages.error(request, 'Выберите время и стрижку')
                return render(request, 'barbershop/barbershop.html')

        else:
            if time and service:
                if phone.isdigit() and len(phone) == 10:
                    if name.isalpha() and len(name) >= 2:
                        service_id = Price.objects.get(service = service).id
                        name = name.capitalize()
                        phone = '+7 %s %s-%s-%s' %(phone[0:3],phone[3:6],phone[6:8], phone[8:10])

                        element = Appointment(name = name,
                                        phone = phone,
                                        day = day,
                                        time = time,
                                        barber_id = barber_id,
                                        service_id = service_id,
                                        client_id = user_id,
                                        )
                        
                        element.save()

                        message_discount = ''

                        dict_obj = {
                            'name': name,
                            'day': day,
                            'time': time,
                            'message_discount': message_discount
                            }
                        
                        return render(request, 'appointment/thanks.html', dict_obj)
                    else:
                        messages.error(request, 'Имя должно состоять только из букв')
                        return render(request, 'barbershop/barbershop.html')
                else:
                    messages.error(request, 'Номер телефона должен состоять из 10 цифр')
                    return render(request, 'barbershop/barbershop.html')
            else:
                messages.error(request, 'Выберите время и стрижку')
                return render(request, 'barbershop/barbershop.html')
    else:
        # return render(request, 'appointment/thanks.html')
        pass

barbershop/appointment/templates/appointment/appointment.html
{% load static %}
{% load phonenumber %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/air-datepicker.css' %}" type="text/css">
    <title>BarberShop-Appointment</title>
</head>
<body>
    <div class="container" id="appointment-container">
        <div class="py-3 text-center">
          <h1 class="h2">Запись к барберу</h1>
        </div>
    <div class="row g-3" id="appointment-content">
        {% if step_1 %}
        <div class="col-md-5 col-lg-4 order-md-last" id="appointment-baner">
            <img class="d-block mx-auto mb-4" src="../../static/barbershop/logo.jpg" alt="логотип BarberShop" width="290" height="">
        </div>
        {% endif %}   

        {% if step_2 %}
        <!-- price list -->
        <div class="col-md-5 col-lg-4 order-md-last" id="product-col3">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Прайс-лист</span>
          </h4>
          <ul class="list-group mb-3">
            {% for service in price_list %}
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-1">{{ service.service }}</h6>
              </div>
              <span class="text-muted">{{ service.price }}₽</span>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!-- ЗАПИСАТЬСЯ -->
        <div class="col-md-7 col-lg-8" id="appointment">
            <div class="row g-3">
                
              {% if step_1 %}
              <form>
              <h4 class="mb-3">Ваш барбер: <b>{{ barber }}</b></h4>
              <h5>Выходные дни барбера:</h5>
              {% for day in list_holiday2 %}
              <div class="box" id="box-holiday">
                <p>{{day}}</p>
              </div>

              {% endfor %}
              <input type="hidden" name="barber"  
              value="{{ barber }}"> 
    
              <div class="col-sm-6">
                <label for="lastName" class="form-label" id="appointment-date">Когда Вас ждать?</label>
                <input type="hidden" class="form-control" name="date" id="airdatepicker">
              </div>

              <div class="container-step">
                <button class="btn btn-primary btn-lg btn-block" id="appointment-step1" type="submit">Далее</button>
                <a href="{% url 'appointment:appointment-barber' %}" id="a-step2">
                    Перевыбрать барбера
                </a>
            </div>

            </form>
              {% endif %}

              {% if step_2 %}
              <h4 class="mb-3">Ваш барбер: <b>{{ barber }}</b> {{ message }}</h4>
              {% if error_switch %}
              <a href="{% url 'appointment:appointment' %}" type="submit">Выбрать другую дату</a>
              {% else %}
              <form action="{% url 'appointment:thanks_page' %}" method="POST">
                {% csrf_token %}
                <div class="col-md-7">
                    <label for="country" class="form-label">Выберите доступное время</label>
                    <select class="form-select" id="appointment-time" name="time">
                      <option value=""></option>
                      {% for time in all_time %}
                      <option value="{{ time }}">{{ time }}</option>
                      {% endfor %}
                    </select>
                  </div>

                <div class="col-md-7">
                    <label for="country" class="form-label">Как будете стричься?</label>
                    <select class="form-select" id="service-appointment" name="service">
                      <option value="">...</option>
                      {% for service in price_list %}
                      <option value="{{ service }}">{{ service }}</option>
                      {% endfor %}
                    </select>
                  </div>
                
                <div class="col-12">
                    <label for="username" class="form-label">Введите ваше имя</label>
                    <div class="input-group">
                      {% if user.is_authenticated %}
                      <input type="text" class="form-control" id="client-name" placeholder="Ваше имя" name="name" value="{{ client.name }}"  readonly>
                      {% else %}
                      <input type="text" class="form-control" id="client-name" placeholder="Ваше имя" name="name">
                      {% endif %}
                </div>
              </div>

              <div class="col-12">
                    <label for="username" class="form-label">Введите ваш номер телефона</label>
                    <div class="input-group">
                      {% if user.is_authenticated %}
                      {% if client.phone_number is null %}
                      <input type="text" class="form-control" id="client-phone" placeholder="Ваш номер (10 цифр без 8)" name="phone">
                      {% else %}
                      <input type="text" class="form-control" id="client-phone" placeholder="Ваш номер (10 цифр без 8)" name="phone" value="{{ client.phone_number|phonenumber }}" readonly>
                      {% endif %}
                      {% else %}
                      <input type="text" class="form-control" id="client-phone" placeholder="Ваш номер (10 цифр без 8)" name="phone">
                      {% endif %}
                </div>
              </div>

                <input type="hidden" name="date"
                    value="{{ choised_day }}">
  
                <input type="hidden" name="barber"  
                    value="{{ barber }}">  
              
                <input type="hidden" name="barber_id"  
                    value="{{ barber_name.id }}">

                  {% if user.is_authenticated %}
                  <input type="hidden" name="user_id"  
                  value="{{ user.id }}">
                  {% else %}
                  <input type="hidden" name="user_id"  
                  value="{{ NULL }}">
                  {% endif %}

                <div class="container-step">
                    <button class="btn btn-primary btn-lg btn-block" id="appointment-step2" type="submit">Оставить заявку</button>
                    <a href="{% url 'appointment:appointment' %}" id="a-step2">
                        Выбрать другую дату
                    </a>
                </div>

            </form>
            {% endif %}
            {% endif %}
            </div>
            <hr class="my-4">
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small" id="footer-appointment">
        <p class="mb-1">© 2023–2023 BarberShop</p>
        <ul class="list-inline">


          <li class="list-inline-item"><a href="{% url 'barbershop:barbershop' %}">BarberShop</a></li>
          <li class="list-inline-item"><a class="telephone" href="tel:8 777 777 77 77">Позвонить</a></li>
          <li class="list-inline-item"><a class="email" href="http://127.0.0.1:8000">Написать</a></li>
        </ul>
      </footer>
    </div>
  
    <script src="{% static 'js/air-datepicker.js' %}"></script>
    <script>
        let minDate = "{{ min_day_value }}"; 
        let maxDate = "{{ max_day_value }}";
        var disabledDays = "{{ days_list }}";


        new AirDatepicker('#airdatepicker', {

            maxDate: new Date(maxDate),
            minDate: new Date(minDate),            
            inline: true,
            isMobile: true,
            autoClose: true,
            // dateFormat: 'dd.mm.yyyy',
            dateFormat: 'yyyy-MM-dd',

            onRenderCell({date, cellType}) {
              if (cellType === 'day') {
                var day = date.getDay(),
                isDisabled = disabledDays.indexOf(day) != -1;
                return {
                  disabled: isDisabled
                }
            }
          }
      });

    </script>

</body>
</html>

barbershop/appointment/templates/appointment/appointment_barber.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/air-datepicker.css' %}" type="text/css">
    <title>BarberShop-Appointment</title>
</head>
<body>
<div class="container" id="appointment-container">
    <div class="py-3 text-center">
      <h1 class="h2">Запись к барберу</h1>
    </div>
<div class="row g-3" id="appointment-content">
<div class="col-md-5 col-lg-4 order-md-last" id="appointment-baner">
    <img class="d-block mx-auto mb-4" src="../../static/barbershop/logo.jpg" alt="логотип BarberShop" width="290" height="">
</div>
<div class="col-md-7 col-lg-8" id="appointment">
    <div class="row g-3">
    <form action="{% url 'appointment:appointment' %}" method="POST">
        {% csrf_token %}
        <div class="col-md-7">
            <label for="country" class="form-label">Выберите барбера</label>
            <select class="form-select" id="appointment-barber" name="barber">
              <option value="">...</option>
                
                {% for barber_name in barber_names %}
                <option value="{{ barber_name }}">{{ barber_name }}</option>
                {% endfor %}
            </select>
        </div>
        <button class="btn btn-primary btn-lg btn-block" id="appointment-step1" type="submit">Далее</button>
        <a href="{% url 'barbershop:barbershop' %}" id="a-step2">
            Вернуться на главную
        </a>
    </form>
</div>
</div>
</div>
</div>
</body>

barbershop/appointment/templates/appointment/thanks.html
{% extends 'barbershop/base.html' %}
{% load static %}
{% block content %}
<div id="thanks">
    <h1 id="h1-thanks">Запись прошла успешно, {{name}}! {{ message_discount }}</h1>
    <h3 id="h3-thanks">Мы ждем вас {{day}} в {{time}} ч.</h3></3>
</div>
{% endblock %}